# Generated by Django 5.2.3 on 2025-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(null=True),
        ),
    ]
